# Site settings
title: ĐẤT CỦ CHI TỈNH LỘ 15 CHÍNH CHỦ - A SƠN 0901188839
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
BÁN ĐẤT CỦ CHI CHÍNH CHỦ TẠI TỈNH LỘ 15 GIÁ 20 TỶ - A SƠN 0901188839 (CHÍNH CHỦ)
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://datcuchi15.github.io/" # the base hostname & protocol for your site
twitter_username: 0901188839
github_username:  0901188839

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
job.title: "Assistant Professor"
excerpt_separator: "<!--more-->"

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""
