# Site settings
title: ĐẤT THỔ CƯ CỦ CHI CHÍNH CHỦ 3000 M2 - 0901188839 - A Sơn
email: 0901188839 - A Sơn
description: > # this means to ignore newlines until "baseurl:"
  Đất thổ cư củ chi chính chủ 500 m2, vị trí đẹp mặt tiền Nguyễn Thị Rành, cách quốc lộ 22, cầu vượt củ chi 2 Km.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "datcuchi.github.io" # the base hostname & protocol for your site
twitter_username: 0901188839 - A Sơn
github_username:  0901188839 - A Sơn

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
job.title: "Assistant Professor"
excerpt_separator: "<!--more-->"

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""
